from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: User Field Select
    Generated by: Phil Minard (pminard1@outlook.com)
    Generated on 01/20/2021, 15:08:42
"""


@pytest.fixture()
def driver():
    capabilities = {
        "platformName": "Android",
        "udid": "emulator-5554",
        "app": "{{APP_PATH}}",
        "appPackage": "{{YOUR_APP_PACKAGE}}",
        "appActivity": "{{YOUR_APP_ACTIVITY}}",
    }
    driver = webdriver.Remote(token="VMpvudCAmswhayszeAdUrDkkfYLqOXbinXcPQe9x-E81", projectname="My first Project", jobname="User Field Select", desired_capabilities=capabilities)
    step_settings = StepSettings(timeout=15000, sleep_time=500, sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Select and entry."""


    # 1. "Reset App"
    # "Clear application data and restart (Auto-generated)"
    driver.reset()

    # 2. "Click 'A fake login screen for testing'"
    a_fake_login_screen_for_testing = driver.find_element(By.XPATH, "//android.widget.TextView[@text = 'A fake login screen for testing']")
    a_fake_login_screen_for_testing.click()

    # 3. "Click 'username'"
    username = driver.find_element(By.XPATH, "//android.widget.EditText[@content-desc = 'username']")
    username.click()

    # 4. "Type 'jwhfaorug' in 'username'"
    username = driver.find_element(By.XPATH, "//android.widget.EditText[@content-desc = 'username']")
    username.send_keys("jwhfaorug")

    # 5. "Click 'password'"
    password = driver.find_element(By.XPATH, "//android.widget.EditText[@content-desc = 'password']")
    password.click()

    # 6. "Type 'aherbglaer' in 'password'"
    password = driver.find_element(By.XPATH, "//android.widget.EditText[@content-desc = 'password']")
    password.send_keys("aherbglaer")

    # 7. "Click 'Login'"
    login = driver.find_element(By.XPATH, "//android.view.ViewGroup/android.widget.TextView[@text = 'Login']")
    login.click()

    # 8. "Click 'Invalid login credentials, please try...'"
    invalid_login_credentials_please_try_ = driver.find_element(By.ID, "android:id/message")
    invalid_login_credentials_please_try_.click()

    # 9. "Click 'Invalid login credentials, please try...'"
    invalid_login_credentials_please_try_ = driver.find_element(By.ID, "android:id/message")
    invalid_login_credentials_please_try_.click()

    # 10. "Click 'OK'"
    ok = driver.find_element(By.ID, "android:id/button1")
    ok.click()

    # 11. "Click 'username'"
    username = driver.find_element(By.XPATH, "//android.widget.EditText[@content-desc = 'username']")
    username.click()

    # 12. "Type 'alice' in 'username'"
    username = driver.find_element(By.XPATH, "//android.widget.EditText[@content-desc = 'username']")
    username.send_keys("alice")

    # 13. "Click 'password'"
    password = driver.find_element(By.XPATH, "//android.widget.EditText[@content-desc = 'password']")
    password.click()

    # 14. "Type 'mypassword' in 'password'"
    password = driver.find_element(By.XPATH, "//android.widget.EditText[@content-desc = 'password']")
    password.send_keys("mypassword")

    # 15. "Click 'Login'"
    login = driver.find_element(By.XPATH, "//android.view.ViewGroup/android.widget.TextView[@text = 'Login']")
    login.click()

    # 16. "Click 'Secret Area'"
    secret_area = driver.find_element(By.XPATH, "//android.widget.TextView[@text = 'Secret Area']")
    secret_area.click()

    # 17. "Click 'Secret Area'"
    secret_area = driver.find_element(By.XPATH, "//android.widget.TextView[@text = 'Secret Area']")
    secret_area.click()

    # 18. "Click 'Logout'"
    logout = driver.find_element(By.XPATH, "//android.widget.TextView[@text = 'Logout']")
    logout.click()

    # 19. "Click 'ANDROID.WIDGET.IMAGEBUTTON'"
    android_widget_imagebutton = driver.find_element(By.XPATH, "//android.widget.ImageButton")
    android_widget_imagebutton.click()


